### ISSUE TITLE
LizardsAndPumpkins\Import\RestApi\CatalogImportApiV2PutRequestHandler::getDataVersionFromRequest() might return int

### ISSUE THREAD

**Issue by Schrank** [lizards-and-pumpkins/catalog#1092]
```
2018/01/13 00:30:31 [error] 21850#21850: *79 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of LizardsAndPumpkins\Import\RestApi\CatalogImportApiV2PutRequestHandler::getDataVersionFromRequest() must be of the type string, integer returned in /var/www/lap/vendor/lizards-and-pumpkins/catalog/src/Import/RestApi/CatalogImportApiV2PutRequestHandler.php:109
Stack trace:
#0 /var/www/lap/vendor/lizards-and-pumpkins/catalog/src/Import/RestApi/CatalogImportApiV2PutRequestHandler.php(94): LizardsAndPumpkins\Import\RestApi\CatalogImportApiV2PutRequestHandler->getDataVersionFromRequest(Object(LizardsAndPumpkins\Http\HttpPutRequest))
#1 /var/www/lap/vendor/lizards-and-pumpkins/catalog/src/Import/RestApi/CatalogImportApiV2PutRequestHandler.php(68): LizardsAndPumpkins\Import\RestApi\CatalogImportApiV2PutRequestHandler->createDataVersion(Object(LizardsAndPumpkins\Http\HttpPutRequest))
#2 /var/www/lap/vendor/lizards-and-pumpkins/catalog/src/Http/WebFront.php(53): LizardsAndPumpkins\Import\RestApi\CatalogImportApiV2PutRequestHandler->process(Object(Li" while reading response header from upstream, client: 52.59.247.201, server: demo.lap-demo.de, request: "PUT /fr/api/catalog_import/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "demo.lap-demo.de"

**Comment by tim-bezhashvyly** [comment]
This is a very good question. Should the output type of data version be unified? Should non-string input be allowed?

**Comment by Schrank** [comment]
I think unifying it, makes validation easier and prevents implicit type casts and unexpected behaviour.

So yes, let's unify it.

**Comment by tim-bezhashvyly** [comment]
What if JSON will contain an array, null, boolean or some other non-sense?

**Comment by Schrank** [comment]
Correct me if I'm missing something out: We want a string in the end.

So there are three options
- We cast it explicitly (intransparent for user)
- PHP casts it implicit (intransparent for user and us)
- they submit a string

So I would throw an exception
